accounts/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path

from . import views

app_name = "accounts"

urlpatterns = [
    path("", views.sign_in, name="sign_in"),
    path("lecturer-sign-up/", views.lecturer_signup, name="lecturer_signup"),
    path("student-sign-up/", views.student_signup, name="student_signup"),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    path("validate-username/", views.validate_username, name="validate_username"),
    path("validate-email/", views.validate_email, name="validate_email"),
    path(
        "validate-lecturer-email/", views.validate_lecturer_email, name="validate_lecturer_email"
    ),
    path("sent/", views.activation_sent_view, name="activation_sent"),
    path("activate/<uidb64>/<token>/", views.activate, name="activate"),
    # path('complete-profile/', complete_profile, name='complete_profile'),
]

oas/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("assignments.urls", namespace="assignments")),
    path("accounts/", include("accounts.urls", namespace="accounts")),
    path(
        "password-reset/",
        auth_views.PasswordResetView.as_view(
            html_email_template_name="registration/password_reset_email.html"
        ),
        name="password_reset",
    ),
    path(
        "password-reset-confirm/<uidb64>/<token>/",
        auth_views.PasswordResetConfirmView.as_view(),
        name="password_reset_confirm",
    ),
    path(
        "password-reset-done/",
        auth_views.PasswordResetDoneView.as_view(),
        name="password_reset_done",
    ),
    path(
        "password-reset-complete/",
        auth_views.PasswordResetCompleteView.as_view(),
        name="password_reset_complete",
    ),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
import uuid

from django.contrib.auth.models import AbstractUser
from django.db import models

from assignments.models import Courses, Department, School

level_choices = (
    ("100L", "100L"),
    ("200L", "200L"),
    ("300L", "300L"),
    ("400L", "400L"),
    ("500L", "500L"),
)

alias_choice = (("Mr.", "Mr."), ("Mrs", "Mrs"), ("Dr.", "Dr."), ("Prof.", "Prof."))

gender_choices = (
    ("Male", "Male"),
    ("Female", "Female"),
)


class User(AbstractUser):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    is_student = models.BooleanField(default=False)
    is_lecturer = models.BooleanField(default=False)
    school = models.ForeignKey(School, on_delete=models.CASCADE, null=True, blank=True)
    department = models.ForeignKey(Department, on_delete=models.CASCADE, null=True, blank=True)
    alias = models.CharField(choices=alias_choice, max_length=5, null=True, blank=True)
    level = models.CharField(choices=level_choices, max_length=11, null=True, blank=True)
    gender = models.CharField(choices=gender_choices, max_length=6)
    courses = models.ManyToManyField(Courses, blank=True)
    has_logged_in = models.BooleanField(default=False)

    def __str__(self):
        return str(self.id)

accounts/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm

from assignments.models import School


class StudentRegistrationForm(UserCreationForm):
    username = forms.CharField(
        widget=forms.TextInput(attrs={"placeholder": "Matric number e.g. CPE/34/2367"})
    )

    def __init__(self, *args, **kwargs):
        super(StudentRegistrationForm, self).__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs["class"] = "validate"

    class Meta:
        model = get_user_model()
        fields = (
            "first_name",
            "last_name",
            "username",
            "email",
            "level",
            "gender",
            "password1",
            "password2",
        )


class LecturerRegistrationForm(UserCreationForm):
    school = forms.ModelChoiceField(queryset=School.objects.all(), empty_label=None)

    def __init__(self, *args, **kwargs):
        super(LecturerRegistrationForm, self).__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs["class"] = "validate"

    class Meta:
        model = get_user_model()
        fields = (
            "first_name",
            "last_name",
            "email",
            "school",
            "gender",
            "password1",
            "password2",
        )


class LoginForm(forms.Form):
    username = forms.CharField(widget=forms.TextInput(attrs={"placeholder": "Username or Email"}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={"placeholder": "Password"}))

    def __init__(self, *args, **kwargs):
        super(LoginForm, self).__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs["class"] = "validate"

accounts/views.py
import json

from django.conf import settings
from django.contrib import messages
from django.contrib.auth import authenticate, get_user_model, login
from django.contrib.sites.shortcuts import get_current_site
from django.http import JsonResponse
from django.shortcuts import redirect, render
from django.urls.base import reverse
from django.utils.encoding import force_bytes, force_text
from django.utils.http import urlsafe_base64_decode, urlsafe_base64_encode

from . import tasks, utils
from .forms import LecturerRegistrationForm, LoginForm, StudentRegistrationForm
from .tokens import account_activation_token


def student_signup(request):
    form = StudentRegistrationForm(request.POST or None)
    if request.method == "POST":
        post_data = request.POST.copy()
        email = post_data.get("email")
        username = post_data.get("username").replace("/", "")
        password = post_data.get("password1")

        if utils.is_valid_email(email):
            user = get_user_model().objects.create(email=post_data.get("email"))

        if utils.is_password_validated(password, user) and utils.is_valid_username(username):
            user.set_password(password)
            user.username = username
            user.first_name = post_data.get("first_name")
            user.last_name = post_data.get("last_name")
            user.level = post_data.get("level")
            user.gender = post_data.get("gender")
            user.is_active = False
            user.is_student = True
            user.save()
            subject = "Please Activate Your Student Account"
            ctx = {
                "fullname": user.get_full_name(),
                "domain": str(get_current_site(request)),
                "uid": urlsafe_base64_encode(force_bytes(user.pk)),
                "token": account_activation_token.make_token(user),
            }

            if settings.DEBUG:
                tasks.send_email_message.delay(
                    subject=subject,
                    template_name="accounts/activation_request.txt",
                    user_id=user.id,
                    ctx=ctx
                )
            else:
                tasks.send_email_message.delay(
                    subject=subject,
                    template_name="accounts/activation_request.html",
                    user_id=user.id,
                    ctx=ctx
                )
            raw_password = password
            user = authenticate(username=username, password=raw_password)
            return JsonResponse(
                {
                    "success": True,
                    "msg": "Your account has been created! You need to verify your email address to be able to log in.",
                    "next": reverse("accounts:activation_sent"),
                }
            )
        else:
            get_user_model().objects.get(email=post_data.get("email")).delete()
            return JsonResponse(
                {
                    "success": False,
                    "msg": "Check your credentials: your password, username, and email! Ensure you adhere to all the specified measures.",
                }
            )
    context = {"page_title": "Student registration", "form": form}
    return render(request, "accounts/student_signup.html", context)


def lecturer_signup(request):
    form = LecturerRegistrationForm(request.POST or None)
    if request.method == "POST":
        if form.is_valid():
            email = form.cleaned_data.get("email")
            password = form.cleaned_data.get("password1")
            if not utils.is_valid_email_lecturer(email):
                messages.error(request, "Email address is not recognized...")
            else:
                user = form.save(commit=False)
                username = str(email.split("@")[0]) + str(utils.random_string_generator())
                user.username = username
                user.is_active = False
                user.is_lecturer = True
                user.save()
                subject = "Please Activate Your Lecturer Account"
                ctx = {
                    "fullname": user.get_full_name(),
                    "domain": str(get_current_site(request)),
                    "uid": urlsafe_base64_encode(force_bytes(user.pk)),
                    "token": account_activation_token.make_token(user),
                }
                if settings.DEBUG:
                    tasks.send_email_message.delay(
                        subject, "accounts/activation_request.txt", user.id, ctx
                    )
                else:
                    tasks.send_email_message.delay(
                        subject, "accounts/activation_request.html", user.id, ctx
                    )
                user = authenticate(username=username, password=password)
                return redirect("accounts:activation_sent")
        else:
            messages.error(request, "Form is not valid. Make corrections and try again.")
    context = {"page_title": "Lecturer registration", "form": form}
    return render(request, "accounts/lecturer_signup.html", context)

def sign_in(request):
    form = LoginForm(request.POST or None)
    msg = "Enter your credentials"
    if request.method == "POST":
        if form.is_valid():
            username = form.cleaned_data.get("username").replace("/", "")
            password = form.cleaned_data.get("password")
            user = authenticate(username=username, password=password)
            if user is not None:
                if user.is_active:
                    login(request, user, backend="accounts.authentication.EmailAuthBackend")
                    messages.success(request, f"Login successful!")
                    if "next" in request.POST:
                        return redirect(request.POST.get("next"))
                    else:
                        return redirect("assignments:index")
                else:
                    messages.error(
                        request,
                        f"Login unsuccessful! Your account has not been activated.Activate your account via {reverse('accounts:resend_email')}",
                    )
                    msg = "Inactive account details"
            else:
                messages.error(request, f"No user with the provided details exists in our system.")
        else:
            messages.error(request, f"Error validating the form")
            msg = "Error validating the form"
    context = {
        "form": form,
        "page_title": "Sign in",
        "msg": msg,
        "section": "signin",
    }
    return render(request, "accounts/sign_in.html", context)


def validate_email(request):
    email = request.POST.get("email", None)
    validated_email = utils.validate_email(email)
    res = JsonResponse({"success": True, "msg": "Valid e-mail address"})
    if not validated_email["success"]:
        res = JsonResponse({"success": False, "msg": validated_email["reason"]})
    return res


def validate_lecturer_email(request):
    email = request.POST.get("email", None)
    validated_email = utils.validate_email_lecturer(email)
    res = JsonResponse({"success": True, "msg": "Valid e-mail address"})
    if not validated_email["success"]:
        res = JsonResponse({"success": False, "msg": validated_email["reason"]})
    return res


def validate_username(request):
    username = request.POST.get("username", None).replace("/", "")
    validated_username = utils.validate_username(username)
    res = JsonResponse({"success": True, "msg": "Valid matriculation number."})
    if not validated_username["success"]:
        res = JsonResponse({"success": False, "msg": validated_username["reason"]})
    return res


def activate(request, uidb64, token):
    try:
        uid = force_text(urlsafe_base64_decode(uidb64))
        user = get_user_model().objects.get(pk=uid)
    except (TypeError, ValueError, OverflowError):
        user = None
    # checking if the user exists, if the token is valid.
    if user is not None and account_activation_token.check_token(user, token):
        # if valid set active true
        user.is_active = True
        user.save()
        messages.success(
            request, f"Your email has been verified successfully! You are now able to log in."
        )
        return redirect("accounts:sign_in")
    else:
        return render(request, "accounts/activation_invalid.html")


def activation_sent_view(request):
    return render(request, "accounts/activation_sent.html")

templates/accounts/activation_invalid.html
{% extends 'base.html' %}
<!-- title -->
{% block title %} Verification email failed {% endblock title %}
<!-- static files -->
{% load static %}
<!-- content starts -->
{% block content %}

<div class="row center-content">
  <div class="col s12" style="max-width: 30rem">
    <div class="card blue-grey darken-1">
      <div class="card-content white-text">
        <span class="card-title">Invalid activation link!!</span>
        <p>
          Oops! There were issues with the activation link, it was highly
          perceived to have been used before... Please, consider requesting for
          an
          <a
            href="{% url 'accounts:resend_email' %}"
            class="btn waves-effect waves-light"
            >activate link resend</a
          >.
        </p>
      </div>
    </div>
  </div>
</div>
<!-- content ends -->
{% endblock content %}

templates/accounts/activation_resent.html
{% extends 'base.html' %}
<!-- title -->
{% block title %} Activation link resent {% endblock title %}
<!-- static files -->
{% load static %}
<!-- content starts -->
{% block content %}

<div class="row">
  <div class="col s6 offset-s3 m6">
    <div class="card blue-grey darken-1">
      <div class="card-content white-text">
        <span class="card-title">Thank you!</span>
        <p>
          A mail has been sent to the e-mail address you provided for
          confirmation.
        </p>
        <p>
          Make sure you visit the link provided in mail as it will soon be
          revoked.
        </p>
      </div>
    </div>
  </div>
</div>
<!-- content ends -->
{% endblock content %}

templates/accounts/activation_sent.html
{% extends 'base.html' %}
<!-- title -->
{% block title %} Verification email sent {% endblock title %}
<!-- static files -->
{% load static %}
<!-- content starts -->
{% block content %}

<div class="row center-content">
  <div class="col s12" style="max-width: 30rem">
    <div class="card blue-grey darken-1">
      <div class="card-content white-text">
        <span class="card-title">Thank you for creating an account!</span>
        <p>
          An email has been sent to the e-mail address you provided during
          registeration for confirmation.
        </p>
        <p>
          Make sure you visit the link provided in mail as it will soon be
          revoked.
        </p>
      </div>
    </div>
  </div>
</div>

<!-- content ends -->
{% endblock content %}

templates/accounts/complete_profile.html
{% extends "base.html" %}

;{% load static %}
{% block title %}Complete Profile{% endblock %}
 {% block navbar %}
    <div class="nav-wrapper">
        <div class="navstyle">
            <a id="logo" href="{% url 'home'%}">AMS</a>
          <ul class="menu">

              <li><a href="{% url 'logout' %}">Logout</a></li>
          </ul>
        </div>
    </div>


  {% endblock %}

{% block content%}

<h4 id="signup-text">Complete Your Profile</h4>
<div class="form-container">

    <div class="signup_form custom">

        <form method="POST" action="">

            {% csrf_token %}

            <div class="form-input-field">
                <label for="school"> School* </label>
                {{ profile_form.school }}
            </div>

            <div class="form-input-field">
                <label for="department"> Department* </label>
                {{ profile_form.department }}
            </div>
            <div class="form-input-field">
                <label for="department"> Courses* </label>
                {{ profile_form.courses }}
            </div>
            <div class="form-input-field">
                <label for="gender"> Gender* </label>
                {{ profile_form.gender }}
            </div>
            <div class="form-input-field">
                <label for="gender"> Role* </label>

                {{ profile_form.role }}
            </div>

            <div class="form-input-field">
                <label for="level"> Level </label>
                {{ profile_form.level }}
            </div>
            <div class="form-input-field">
                <label for="alias"> Alias </label>

                {{ profile_form.alias }}
            </div>
            <button class="btn waves-effect waves-light" type="submit" name="signup">Create Profile
                <i class="material-icons right">send</i>
            </button>
        </form>


    </div>
    <div class="signup-illustration">
        <img src="{% static 'img/sign-up-illustration.svg' %}" alt="Sign up illustration">
    </div>

</div>
<script>
    {% if message %}
    Materialize.toast('{{ message }}', 2000, 'red');
    {% endif %}
</script>
</div>

{% endblock %}

templates/accounts/lecturer_signup.html
{% extends "base.html" %}
<!---->
{% load static %}
<!---->
{% block title %}{{page_title}}{% endblock %}
<!---->
{% block content%}

<h4 id="signup-text">Create an Account</h4>
<div class="form-container">
  <div class="signup_form">
    <form method="POST" action="" class="col s12" id="signup_form">
      <div class="materialert error" id="materialAlert">
        <div class="material-icons">report_problem</div>
        <span id="alertText">Stop</span>
        <button type="button" class="close-alert" id="closeAlert">×</button>
      </div>
      {% csrf_token %}
      <div class="row">
        <div class="input-field col s12">
          <i class="material-icons prefix">email</i>
          <label for="id_email"> Email* </label>
          {{ form.email }}
          <span class="helper-text email-error"></span>
          {% if form.email.errors %}
          <span class="helper-text email-error">{{form.email.errors}}</span>
          {% endif %}
        </div>
      </div>
      <div class="row">
        <div class="input-field col s6">
          <i class="material-icons prefix">account_circle</i>
          <label for="id_first_name"> First Name*</label>
          {{ form.first_name }}
          <!---->
          {% if form.first_name.errors %}
          <span class="helper-text">{{form.first_name.errors}}</span>
          {% endif %}
        </div>
        <div class="input-field col s6">
          <i class="material-icons prefix">account_circle</i>
          <label for="id_last_name">Last Name*</label>
          {{ form.last_name }}
          <!---->
          {% if form.last_name.errors %}
          <span class="helper-text">{{form.last_name.errors}}</span>
          {% endif %}
        </div>
      </div>

      <div class="row">
        <div class="input-field col s6">
          <i class="material-icons prefix">school</i>
          <label for="id_school">School* </label>
          {{ form.school }}
          <!---->
          {% if form.school.errors %}
          <span class="helper-text">{{form.school.errors}}</span>
          {% endif %}
        </div>
        <div class="input-field col s6">
          <i class="material-icons prefix">face</i>
          <label for="id_gender">Gender* </label>
          {{ form.gender }}
          <!---->
          {% if form.gender.errors %}
          <span class="helper-text">{{form.gender.errors}}</span>
          {% endif %}
        </div>
      </div>
      <div class="row">
        <div class="input-field col s6">
          <i class="material-icons prefix">vpn_key</i>
          <label for="id_password1">Password* </label>
          {{ form.password1 }}
          <!---->
          {% if form.password1.errors %}
          <span class="helper-text">{{form.password1.errors}}</span>
          {% endif %}
          <!---->
          <span class="helper-text">{{ form.password1.help_text }}</span>
        </div>
        <div class="input-field col s6">
          <i class="material-icons prefix">vpn_key</i>
          <label for="id_password2">Confirm password* </label>
          {{ form.password2 }}
          <!---->
          {% if form.password2.errors %}
          <span class="helper-text">{{form.password2.errors}}</span>
          {% endif %}
          <!---->
        </div>
      </div>

      <button
        class="btn waves-effect waves-light btn-large disabled"
        type="submit"
        id="signup-btn"
      >
        <div class="loader" id="loader">
          <div class="loading"></div>
        </div>
        Sign up
        <i class="material-icons right">send</i>
      </button>
    </form>
  </div>
  <div class="signup-illustration">
    <img
      src="{% static 'img/sign-up-illustration.svg' %}"
      alt="Sign up illustration"
    />
  </div>
</div>

{% endblock %}

<!---->
{% block js %}
<script>
  document.getElementById("materialAlert").style.display = "none";
  const signUpForm = document.getElementById("signup_form");
  const formElements = document.querySelectorAll(
    "#signup_form  input, #signup_form  select"
  );
  signUpForm.addEventListener("keyup", (event) => {
    let empty = false;
    formElements.forEach((element) => {
      if (element.value === "") {
        empty = true;
      }
    });
    if (signUpForm.password1.value !== signUpForm.password2.value) {
      empty = true;
    }
    if (empty) {
      $("#signup-btn").addClass("disabled");
    } else {
      $("#signup-btn").removeClass("disabled");
    }
  });

  const validateEmail = function (email) {
    var formData = new FormData();
    formData.append("email", email);
    $.ajax({
      url: "{% url 'accounts:validate_lecturer_email' %}",
      type: "POST",
      dataType: "json",
      cache: false,
      processData: false,
      contentType: false,
      data: formData,
      error: function (xhr) {
        console.error(xhr.statusText);
      },
      success: function (res) {
        if (!res.success) {
          $(".email-error").css("color", "red");
          $("#id_email").addClass("invalid");
          $(".email-error").text(res.msg);
        } else {
          $(".email-error").css("color", "green");
          $("#id_email").removeClass("invalid");
          $("#id_email").addClass("valid");
          $(".email-error").text(res.msg);
        }
      },
    });
  };
  $("#id_email").on("keyup", (event) => {
    event.preventDefault();
    const email = event.target.value;
    validateEmail(email);
  });
  $("#id_email").on("change", (event) => {
    event.preventDefault();
    const email = event.target.value;
    validateEmail(email);
  });
</script>
{% endblock js %}

templates/accounts/student_signup.html
{% extends "base.html" %}
<!--static-->
{% load static %}
<!--title-->
{% block title %}{{page_title}}{% endblock %}
<!--content-->
{% block content%}

<h4 id="signup-text">Create an Account</h4>
<div class="form-container">
  <!--    Student Sign Up-->

  <div class="signup_form">
    <form method="POST" action="" class="col s12" id="signup_form">
      <div class="materialert error" id="materialAlert">
        <div class="material-icons">report_problem</div>
        <span id="alertText">Stop</span>
        <button type="button" class="close-alert" id="closeAlert">×</button>
      </div>
      {% csrf_token %}
      <div class="row">
        <div class="input-field col s6">
          <i class="material-icons prefix">account_box</i>
          <label for="id_username"> Matric No* </label>
          {{ form.username }}
          <span class="helper-text username-error"></span>
        </div>
        <div class="input-field col s6">
          <i class="material-icons prefix">email</i>
          <label for="id_email"> Email* </label>
          {{ form.email }}
          <span class="helper-text email-error"></span>
        </div>
      </div>
      <div class="row">
        <div class="input-field col s6">
          <i class="material-icons prefix">account_circle</i>
          <label for="id_first_name"> First Name*</label>
          {{ form.first_name }}
        </div>
        <div class="input-field col s6">
          <i class="material-icons prefix">account_circle</i>
          <label for="id_last_name">Last Name*</label>
          {{ form.last_name }}
        </div>
      </div>

      <div class="row">
        <div class="input-field col s6">
          <i class="material-icons prefix">grade</i>
          <label for="id_level">Level </label>
          {{ form.level }}
        </div>
        <div class="input-field col s6">
          <i class="material-icons prefix">face</i>
          <label for="id_gender">Gender </label>
          {{ form.gender }}
        </div>
      </div>
      <div class="row">
        <div class="input-field col s6">
          <i class="material-icons prefix">vpn_key</i>
          <label for="id_password1">Password* </label>
          {{ form.password1 }}
          <span class="helper-text">{{ form.password1.help_text }}</span>
        </div>
        <div class="input-field col s6">
          <i class="material-icons prefix">vpn_key</i>
          <label for="id_password2">Confirm password* </label>
          {{ form.password2 }}
        </div>
      </div>

      <button
        class="btn waves-effect waves-light btn-large disabled"
        type="submit"
        id="signup-btn"
      >
        <div class="loader" id="loader">
          <div class="loading"></div>
        </div>
        Sign up
        <i class="material-icons right">send</i>
      </button>
    </form>
  </div>
  <div class="signup-illustration">
    <img
      src="{% static 'img/sign-up-illustration.svg' %}"
      alt="Sign up illustration"
    />
  </div>
</div>
<script>
  {% if message %}
  Materialize.toast('{{ message }}', 2000, 'red');
  {% endif %}
</script>

{% endblock %}
<!--js-->

{% block js %}
<script>
  document.getElementById("materialAlert").style.display = "none";
  const signUpForm = document.getElementById("signup_form");
  const formElements = document.querySelectorAll(
    "#signup_form  input, #signup_form  select"
  );
  signUpForm.addEventListener("keyup", (event) => {
    let empty = false;
    formElements.forEach((element) => {
      if (element.value === "") {
        empty = true;
      }
    });
    if (signUpForm.password1.value !== signUpForm.password2.value) {
      empty = true;
    }
    if (empty) {
      $("#signup-btn").addClass("disabled");
    } else {
      $("#signup-btn").removeClass("disabled");
    }
  });

  const validateEmail = function (email) {
    var formData = new FormData();
    formData.append("email", email);
    $.ajax({
      url: "{% url 'accounts:validate_email' %}",
      type: "POST",
      dataType: "json",
      cache: false,
      processData: false,
      contentType: false,
      data: formData,
      error: function (xhr) {
        console.error(xhr.statusText);
      },
      success: function (res) {
        if (!res.success) {
          $(".email-error").css("color", "red");
          $("#id_email").addClass("invalid");
          $(".email-error").text(res.msg);
        } else {
          $(".email-error").css("color", "green");
          $("#id_email").removeClass("invalid");
          $("#id_email").addClass("valid");
          $(".email-error").text(res.msg);
        }
      },
    });
  };
  const validateUsername = function (username) {
    var formData = new FormData();
    formData.append("username", username);

    $.ajax({
      url: "{% url 'accounts:validate_username' %}",
      type: "POST",
      dataType: "json",
      cache: false,
      processData: false,
      contentType: false,
      data: formData,
      error: function (xhr) {
        console.error(xhr.statusText);
      },
      success: function (res) {
        if (!res.success) {
          $(".username-error").css("color", "red");
          $("#id_username").addClass("invalid");
          $(".username-error").text(res.msg);
        } else {
          $(".username-error").css("color", "green");
          $("#id_username").removeClass("invalid");
          $("#id_username").addClass("valid");
          $(".username-error").text(res.msg);
        }
      },
    });
  };

  $("#id_username").on("keyup", (event) => {
    event.preventDefault();
    const username = event.target.value;
    validateUsername(username);
  });
  $("#id_username").on("change", (event) => {
    event.preventDefault();
    const username = event.target.value;
    validateUsername(username);
  });

  $("#id_email").on("keyup", (event) => {
    event.preventDefault();
    const email = event.target.value;
    validateEmail(email);
  });
  $("#id_email").on("change", (event) => {
    event.preventDefault();
    const email = event.target.value;
    validateEmail(email);
  });
  signUpForm.addEventListener("submit", (e) => {
    e.preventDefault();
    if (document.getElementById("loader")) {
      document.getElementById("loader").style.display = "block";
    }
    $("#signup-btn").html("Registering...").addClass("disabled");
    const formData = new FormData(e.target);
    console.log(formData);
    $.ajax({
      url: "{% url 'accounts:student_signup' %}",
      type: "POST",
      dataType: "json",
      data: formData,
      success: (res) => {
        if (res.success) {
          M.toast({ html: `${res.msg}` });
          window.location.href = `${res.next}`;
        } else {
          M.toast({ html: `${res.msg}` });
          document.getElementById("materialAlert").style.display = "block";
          $("#alertText").html(`${res.msg}`);
          // location.reload();
        }
      },
      error: (error) => {
        console.error(error.responseText);
      },
      cache: false,
      processData: false,
      contentType: false,
    });
  });
</script>
{% endblock js %}