accounts/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path

from . import views

app_name = "accounts"

urlpatterns = [
    path("", views.sign_in, name="sign_in"),
    path("lecturer-sign-up/", views.lecturer_signup, name="lecturer_signup"),
    path("student-sign-up/", views.student_signup, name="student_signup"),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    path("validate-username/", views.validate_username, name="validate_username"),
    path("validate-email/", views.validate_email, name="validate_email"),
    path(
        "validate-lecturer-email/", views.validate_lecturer_email, name="validate_lecturer_email"
    ),
    path("sent/", views.activation_sent_view, name="activation_sent"),
    path("activate/<uidb64>/<token>/", views.activate, name="activate"),
    # path('complete-profile/', complete_profile, name='complete_profile'),
]

assignments/urls.py
from django.urls import path
from . import views

app_name = "assignments"

urlpatterns = [
    path("", views.index, name="index"),
]

oas/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("assignments.urls", namespace="assignments")),
    path("accounts/", include("accounts.urls", namespace="accounts")),
    path(
        "password-reset/",
        auth_views.PasswordResetView.as_view(
            html_email_template_name="registration/password_reset_email.html"
        ),
        name="password_reset",
    ),
    path(
        "password-reset-confirm/<uidb64>/<token>/",
        auth_views.PasswordResetConfirmView.as_view(),
        name="password_reset_confirm",
    ),
    path(
        "password-reset-done/",
        auth_views.PasswordResetDoneView.as_view(),
        name="password_reset_done",
    ),
    path(
        "password-reset-complete/",
        auth_views.PasswordResetCompleteView.as_view(),
        name="password_reset_complete",
    ),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/includes/_footer.html
<footer>
  <div class="copyright">
    <div class="footer-container">
      Developed by <a href="#">Owolabi Victor</a>
    </div>
  </div>
</footer>

templates/includes/_header.html
<nav class="light-blue lighten-1" role="navigation">
  <div class="nav-wrapper container">
    <a
      id="logo-container"
      href="{% url 'assignments:index'%}"
      class="brand-logo"
      >AMS</a
    >
    <ul class="right hide-on-med-and-down">
      <li><a href="{% url 'assignments:index' %}">Home</a></li>
      {% if request.user.is_authenticated %}
      <li><a href="#!">Dashboard</a></li>
      <li><a href="{% url 'accounts:logout' %}">Logout</a></li>
      {% else %}
      <li><a href="{% url 'accounts:sign_in' %}">Login</a></li>
      <!-- Dropdown Trigger -->
      <li>
        <a class="dropdown-trigger" href="#!" data-target="signupdropdown"
          >Create Account<i class="material-icons right">arrow_drop_down</i></a
        >
      </li>
      <!-- Dropdown Structure -->
      <ul id="signupdropdown" class="dropdown-content">
        <li><a href="{% url 'accounts:student_signup' %}">Student</a></li>
        <li><a href="{% url 'accounts:lecturer_signup' %}">Lecturer</a></li>
      </ul>

      {% endif %}
    </ul>

    <ul id="nav-mobile" class="sidenav">
      <li><a href="{% url 'assignments:index' %}">Home</a></li>
      {% if request.user.is_authenticated %}
      <li><a href="#!">Dashboard</a></li>
      <li><a href="{% url 'accounts:logout' %}">Logout</a></li>
      {% else %}
      <li><a href="{% url 'accounts:sign_in' %}">Login</a></li>
      <!-- Dropdown Trigger -->
      <li>
        <a
          class="dropdown-trigger"
          href="#!"
          data-target="signupdropdown-mobile"
          >Create Account<i class="material-icons right">arrow_drop_down</i></a
        >
      </li>
      <!-- Dropdown Structure -->
      <ul id="signupdropdown-mobile" class="dropdown-content">
        <li><a href="{% url 'accounts:student_signup' %}">Student</a></li>
        <li><a href="{% url 'accounts:lecturer_signup' %}">Lecturer</a></li>
      </ul>

      {% endif %}
    </ul>
    <a href="#" data-target="nav-mobile" class="sidenav-trigger"
      ><i class="material-icons">menu</i></a
    >
  </div>
</nav>